### PR TITLE
Got rid of webserver, added *things*

### PR DESCRIPTION
**Pull request by FishingHacks**

### CODE REVIEW

**Comment by FishingHacks** [comment]
pls approve my changes uwu~

**Review by FishingHacks — COMMENTED** [review]
Excellent, well done, major improvements we all needed :3

**Comment by FishingHacks** [comment]
**Removed**:
- Weird webserver that does shit

**Added**
- Sizing
- Weird constant called "SZ_MULTIPLIER" with the value of 5.555555555
- Field texture (this determines the size)
- Added fields x, y, w and h to the rendering output, fields starting with __ will get removed
- Moved the types to a common type storage
- Used interprocess comunication instead of some weird webserver
- Added lightmode as default (when you select lightmode in the settings)
- Rerendering on resize

**Bugs**
- Rendering does not work as expected (Fields that appear right next to each other in the document are suddenly not next to each other, everything is scaled up by a factor of 4x, X and Y in field overview are incorrect and not actually representetive of the actual X and Y coordinate in the ending image file, this appears to be a problem with the current version ***too***)
- Crashes when opening a file that does not exist. Can only be closed using SIGKILL, Alt+F4 or the manual call to `window.__api.close();`.

**Comment by RedCrafter07** [comment]
Are the bugs fixed or do they exist with this pull request?

**Pull request merged**
